all :
	clang++ main.cpp book.cpp contact.cpp -Wall -Wextra -Werror -o phonebook
test : all
	./megaphone "shhhhh... I think the students are asleep..."
	./megaphone Damnit " ! " "Sorry students, I thought this thing was off."
	./megaphone