all :
	clang++ megaphone.cpp -Wall -Wextra -Werror -o megaphone
test : all
	./megaphone "shhhhh... I think the students are asleep..."
	./megaphone Damnit " ! " "Sorry students, I thought this thing was off."
	./megaphone